language: node_js
node_js:
  - "8.11.4"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
env:
  global:
    - CC_TEST_REPORTER_ID=25b50f4ff3a03c74feef2c35440d7f549a9bb843025bb4e15183b897460f2e4b
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
