export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
export const OPEN_PUBLISH_MODAL = 'OPEN_PUBLISH_MODAL';
export const CLOSE_PUBLISH_MODAL = 'CLOSE_PUBLISH_MODAL';
export const SHOW_PUBLISH_ERROR = 'SHOW_PUBLISH_ERROR';
export const HIDE_PUBLISH_ERROR = 'HIDE_PUBLISH_ERROR';
