export const SENDING_REQUEST = 'SENDING_REQUEST';
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_ERROR = 'CREATE_ARTICLE_ERROR';
export const OPEN_PUBLISH_MODAL = 'OPEN_PUBLISH_MODAL';
export const CLOSE_PUBLISH_MODAL = 'CLOSE_PUBLISH_MODAL';
export const SHOW_PUBLISH_ERROR = 'SHOW_PUBLISH_ERROR';
export const HIDE_PUBLISH_ERROR = 'HIDE_PUBLISH_ERROR';
export const HIDE_PUBLISH_RESPONSE = 'HIDE_PUBLISH_RESPONSE';

export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_ERROR = 'GET_ARTICLE_ERROR';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR';
