export const LOADING_COMMENTS = 'LOADING_COMMENTS';
export const SENDING_COMMENT = 'SENDING_COMMENT';
export const COMMENT_POSTED = 'COMMENT_POSTED';
export const SHOW_ARTICLE_COMMENTS = 'SHOW_ARTICLE_COMMENTS';
export const SHOW_GET_COMMENTS_ERROR = 'SHOW_GET_COMMENTS_ERROR';
export const SHOW_COMMENT_ERROR = 'SHOW_COMMENT_ERROR';
export const RESET_REFRESH_ARTICLE_COMMENTS = 'RESET_REFRESH_ARTICLE_COMMENTS';
