export const FETCH_NOTIFICATION_REQUEST = 'FETCH_NOTIFICATION_REQUEST';
export const FETCH_NOTIFICATION_SUCCESS = 'FETCH_NOTIFICATION_SUCCESS';
export const FETCH_NOTIFICATION_FAILURE = 'FETCH_NOTIFICATION_FAILURE ';

export const UPDATE_NOTIFICATION_BEGINS = 'UPDATE_NOTIFICATION_BEGINS';
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS';
export const UPDATE_NOTIFICATION_FAILURE = 'UPDATE_NOTIFICATION_FAILURE ';

export const REALTIME_NOTIFICATION_BEGINS = 'REALTIME_NOTIFICATION_BEGINS';
export const REALTIME_NOTIFICATION_SUCCESS = 'REALTIME_NOTIFICATION_BEGINS';
