export const SAVE_INPUT = 'SAVE_INPUT';
export const PASSWORD_RESET_REQUEST = 'PASSWORD_RESET_REQUEST';
export const PASSWORD_RESET_REQUEST_SUCCESS = 'PASSWORD_RESET_REQUEST_SUCCESS';
export const PASSWORD_RESET_REQUEST_FAILURE = 'PASSWORD_RESET_REQUEST_FAILURE';
export const COMPLETE_RESET_REQUEST = 'COMPLETE_PASSWORD_RESET_REQUEST';
export const COMPLETE_RESET_REQUEST_SUCCESS = 'COMPLETE_PASSWORD_RESET_REQUEST_SUCCESS';
export const COMPLETE_RESET_REQUEST_FAILURE = 'COMPLETE_PASSWORD_RESET_REQUEST_FAILURE';
export const INPUT_ERROR = 'PASSWORD_RESET_INPUT_ERROR';
